const { Client, LocalAuth, MessageMedia } = require('whatsapp-web.js');
const qrcode = require('qrcode-terminal');
const puppeteer = require('puppeteer');
const cron = require('node-cron');

// --- Configuration ---
const TARGET_URL = 'https://www.google.com/'; // Must include https://
const TARGET_GROUP_NAME = 'Testuser';
const ALLOWED_USERS = [
    'mobile_no@c.us',
    'mobile_no@c.us',
    ,// YOUR account id generated by WhatsApp Web
];
const TRIGGER_PHRASE = 'current booking status';

// --- Initialize WhatsApp Client ---
const client = new Client({
    authStrategy: new LocalAuth() // Saves session locally
});

client.on('qr', (qr) => {
    qrcode.generate(qr, { small: true });
    console.log('Scan the QR code above with WhatsApp.');
});

client.on('ready', () => {
    console.log('Client is ready! Automation is now running.');
    scheduleAutomatedReports();
});

// --- Helper function to capture the screenshot ---
async function captureScreenshot() {
    let browser;
    try {
        browser = await puppeteer.launch({
            args: ['--no-sandbox', '--disable-setuid-sandbox']
        });
        const page = await browser.newPage();
        await page.setViewport({ width: 1280, height: 800 });

        await page.goto(TARGET_URL, { waitUntil: 'networkidle2', timeout: 60000 });

        const imagePath = './screenshot.png';
        await page.screenshot({ path: imagePath });
        return imagePath;
    } catch (error) {
        console.error('Error capturing screenshot:', error);
        return null;
    } finally {
        if (browser) {
            await browser.close();
        }
    }
}

// --- Helper function to send the screenshot to the group ---
async function sendScreenshotToGroup() {
    const chats = await client.getChats();
    const targetGroup = chats.find(chat => chat.isGroup && chat.name === TARGET_GROUP_NAME);

    if (targetGroup) {
        console.log('Fetching automated scheduled screenshot...');
        const imagePath = await captureScreenshot();

        if (imagePath) {
            const media = MessageMedia.fromFilePath(imagePath);
            await client.sendMessage(targetGroup.id._serialized, media, { caption: 'Automated Booking Status' });
            console.log('Screenshot sent successfully.');
        } else {
            console.log('Failed to generate screenshot, skipping automated message.');
        }
    } else {
        console.log('Scheduled push failed: Group not found.');
    }
}

// --- 1. Listen for messages (Using message_create to catch host account messages) ---
client.on('message_create', async (msg) => {

    // Check if the message is the trigger phrase (case insensitive)
    if (msg.body.toLowerCase().includes(TRIGGER_PHRASE)) {

        // --- DEBUG LOGGER ---
        console.log(`\n[DEBUG] Trigger phrase detected!`);
        console.log(`[DEBUG] Sender ID: "${msg.author || msg.from}"`);

        const chat = await msg.getChat();
        console.log(`[DEBUG] Chat Name: "${chat.name}" | Is Group: ${chat.isGroup}`);

        // Verify it is the correct group
        if (chat.isGroup && chat.name === TARGET_GROUP_NAME) {

            // Verify if the sender is in the allowlist
            if (ALLOWED_USERS.includes(msg.author || msg.from)) {
                console.log(`✅ Success! Trigger received from authorized user. Generating screenshot...`);

                const imagePath = await captureScreenshot();

                if (imagePath) {
                    const media = MessageMedia.fromFilePath(imagePath);
                    await msg.reply(media);
                    console.log('✅ Screenshot sent successfully.');
                } else {
                    await msg.reply('Error: Could not generate the booking status screenshot at this time.');
                }
            } else {
                console.log(`❌ FAILED: Sender ${msg.author || msg.from} is NOT in the ALLOWED_USERS array.`);
            }
        } else {
            console.log(`❌ FAILED: Message is in "${chat.name}", but we only allow "${TARGET_GROUP_NAME}".`);
        }
    }
});

// --- 2. Schedule the automated office-day push ---
function scheduleAutomatedReports() {
    // Runs at 10:00 AM on Monday through Friday
    cron.schedule('0 10 * * 1-5', async () => {
        console.log('Running scheduled office day report...');
        await sendScreenshotToGroup();
    }, {
        scheduled: true,
        timezone: 'Asia/Kolkata'
    });
}

client.initialize();